---
apiVersion: v1
kind: Secret
metadata:
  name: auto-school-basicauth
  namespace: auto-school
type: Opaque
data:
  auth: bG9jaGlzOiQyeSQwNSR6RWRGaWp4TE80ZVNWTXlRMWhwdXJlRkZzeGpKLjhIODd6QW4vVVYxc2ZON2plS2lCQkJh
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auto-school-basicauth
  namespace: auto-school
spec:
  basicAuth:
    secret: auto-school-basicauth
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: auto-school
  namespace: auto-school
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - outbound
  routes:
    - kind: Rule
      match: Host(`school.vanderloch.com`)
      middlewares:
        - name: auto-school-basicauth
      services:
        - name: auto-school
          port: 80
          scheme: http
  tls:
    secretName: lochis-tls
